// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQP5Vg5oSg08TlVp3rGy8lNpM5uIPwKZI',
    appId: '1:515997175207:web:02d82d95d59f9fd86cba82',
    messagingSenderId: '515997175207',
    projectId: 'group7-backend',
    authDomain: 'group7-backend.firebaseapp.com',
    storageBucket: 'group7-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP9Vndv-XyxDXgUBzgNxTJImHmihJlszQ',
    appId: '1:515997175207:android:38fa149b313312f26cba82',
    messagingSenderId: '515997175207',
    projectId: 'group7-backend',
    storageBucket: 'group7-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1O-fEFafyNjZqpq546QZI3pcuz5JnPuE',
    appId: '1:515997175207:ios:827a52ce524db0d16cba82',
    messagingSenderId: '515997175207',
    projectId: 'group7-backend',
    storageBucket: 'group7-backend.firebasestorage.app',
    iosBundleId: 'com.example.clickCounter',
  );
}
